---
- name: install Docker
  hosts: all
  become: true
  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

    - name: Git clone
      ansible.builtin.git:
        repo: https://github.com/lopnesh/edu-repo.git
        dest: /src/edu-repo
    
    - name: Copy shell script
      ansible.builtin.copy:
        src: docker-up.sh
        dest: /usr/bin/docker-up.sh
        owner: root
        group: root
        mode: u+rw,g+rw,o+rwx

    - name: Copy service file
      ansible.builtin.copy:
        src: docker-up.service
        dest: /lib/systemd/system/docker-up.service 
        owner: root
        group: root
        mode: '0644'

    - name: Just force systemd to re-execute itself
      ansible.builtin.systemd:
        daemon_reexec: yes

    - name: Enable service docker-up
      ansible.builtin.systemd:
        name: docker-up
        enabled: yes
        