FROM mysql:8.0

ENV MYSQL_DATABASE blog
ENV MYSQL_ROOT_PASSWORD toor
ENV MYSQL_USER: user
ENV MYSQL_PASSWORD: pass

COPY ./db/migrations/*.up.sql /docker-entrypoint-initdb.d/
RUN chmod -R 777 /docker-entrypoint-initdb.d/
